[build-system]
requires = [
    "setuptools>=68",
]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-OctoText"
version = "0.3.3.1"
description = "Send text/email messages on common printer events"
authors = [
    { name = "Douglas Krahmer (original: Stephen Berry)", email = "doug.octotext@remhark.com" },
]
requires-python = ">=3.7,<4"
dependencies = []
dynamic = [
    "license",
]

[project.entry-points."octoprint.plugin"]
OctoText = "octoprint_octotext"

[project.urls]
Homepage = "https://github.com/OctoText/OctoText"

[project.optional-dependencies]
develop = [
    "go-task-bin",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = [
    "octoprint_octotext",
    "octoprint_octotext.*",
]
